// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvqssrfmkgnbnkoqqtsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2cXNzcmZta2duYm5rb3FxdHNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNzMzMDEsImV4cCI6MjA1MTc0OTMwMX0.ISz__nAMLLDOfgF5Tx2_zesX4Z8ViF7P5TzhDl33qKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);